# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_test <- function(lambda, sigma, Z, E, L, H, ind) {
    invisible(.Call('epee_do_test', PACKAGE = 'epee', lambda, sigma, Z, E, L, H, ind))
}

